// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvNny2nvlGMayNgB7Fg-8u1YuJtCQAvmc',
    appId: '1:575176127704:web:88360fa7df8160c94ad3ad',
    messagingSenderId: '575176127704',
    projectId: 'phoenix-68fc5',
    authDomain: 'phoenix-68fc5.firebaseapp.com',
    storageBucket: 'phoenix-68fc5.firebasestorage.app',
    measurementId: 'G-RMYBB5Y2GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7P1LObgNN2oCZjsxY3HSiCY79m_A9NAA',
    appId: '1:575176127704:android:f0cb11fc1c461ca24ad3ad',
    messagingSenderId: '575176127704',
    projectId: 'phoenix-68fc5',
    storageBucket: 'phoenix-68fc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXq95BkP9RcTKFmEE-h2sbFygXebVT1hw',
    appId: '1:575176127704:ios:f76554491a9faf814ad3ad',
    messagingSenderId: '575176127704',
    projectId: 'phoenix-68fc5',
    storageBucket: 'phoenix-68fc5.firebasestorage.app',
    iosBundleId: 'app.weesabi.phoenix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXq95BkP9RcTKFmEE-h2sbFygXebVT1hw',
    appId: '1:575176127704:ios:356f32b51450c00b4ad3ad',
    messagingSenderId: '575176127704',
    projectId: 'phoenix-68fc5',
    storageBucket: 'phoenix-68fc5.firebasestorage.app',
    iosBundleId: 'com.example.phoenix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvNny2nvlGMayNgB7Fg-8u1YuJtCQAvmc',
    appId: '1:575176127704:web:aab07067e266ceaf4ad3ad',
    messagingSenderId: '575176127704',
    projectId: 'phoenix-68fc5',
    authDomain: 'phoenix-68fc5.firebaseapp.com',
    storageBucket: 'phoenix-68fc5.firebasestorage.app',
    measurementId: 'G-NTES3SWPEY',
  );

}